version: '3'
services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    user: "solr:root"
    volumes:
      - ./solr-data:/var/solr
      - ./security.json:/var/solr/data/security.json
    command:
      - solr-precreate

  mpp:
    build: ./mpp
    ports:
      - "8005:8005"
    volumes:
      - ./mpp:/app


  wait_for_it:
    build:
      context: ./wait-for-it
      dockerfile: Dockerfile


volumes:
  data:
